import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { FamilySection, Footer, Nav, OffPisteSection, PisteSection, TopSection } from '../src/components/index'

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav/>
        <div className={ styles.sectionsContainer }>
          <TopSection/>
          <PisteSection/>
          <OffPisteSection/>
          <FamilySection/>
        </div>
      </main>
    </>
  )
}

export default Home
